### ISSUE TITLE
Conquering Fears

### ISSUE THREAD

**Issue by justinchmura** [mxriverlynn/ama#12]
I've got a newsletter up and running with about 65 subscribers (which I'm ecstatic about), but I always have that feeling like what I send out isn't quality content. Seeing that you produce content all the time, and content that people pay for, how do you conquer that feeling? I guess it could be classified as imposter syndrome, but more knowing that it's something people want.

Thanks!

**Comment by mxriverlynn** [comment]
> how do you conquer that feeling?

i never have.

every email i send, every screencast i publish, ever sale or product launch... there is a constant fear, worry, nausea with each one. writing this answer right now... i have this voice in my head, saying "I'm not qualified to answer this question. The only reason he's asking is because he doesn't see how hard this is for me, because he only sees it from the other side."

there's a lot of truth in that voice

the key, though, is that i do it anyways. where most people would stop when they face that fear, i try to take one step further. i try to push myself to do just one new thing... one small change. i continuously step in to things that make me very uncomfortable.

sometimes i over-step and try to do too much. or i screw things up and come across as a scammy marketer. sometimes things just don't work. sometimes it does have the desired effect. sometimes the result is something surprisingly different than I hoped for. 

but, if my content is high quality at this point, it's only because i kept pushing and kept producing content, even when i knew it was terrible. i kept producing content, and reading / watching other people's content. i improved because i produced more. it's like taking a pottery class. you can spend a semester studying technique from books and produce one pot at the end that will probably look terrible... or you can get your hands dirty, and produce as many pots as possible during that semester. chances are, you'll have higher quality products at the end if you just keep producing pots as fast as possible. now throw in a fair mix of study with your practice and you'll be making great pots sooner than you thought.

in all of this, there is one thing that has kept me going and helped me to push farther and faster than i would have on my own: my support group. [I've written about it](http://derickbailey.com/email_archive/dont-try-and-do-it-alone/) on my mailing list and we record our weekly sessions at [Entreprogrammers.com](http://entreprogrammers.com). If you don't have a support group, find one or create one. Don't try to make your group look like ours, though. Let your group be what your group needs to be for the people in it. This is also something I talk about in my [5 Stages of Developer Grief presentation](http://derickbailey.com/2015/03/29/the-5-stages-of-developer-grief-spacecityjs-2015-keynote/).
