### ISSUE TITLE
What's your favorite project on GitHub and why?

### ISSUE THREAD

**Issue by arthurvr** [mxriverlynn/ama#14]

**Comment by mxriverlynn** [comment]
probably still marionettejs - because it is the most successful open source project i've created. it took on a life of it's own, and i handed over the reigns to a team a few years ago... but i'm still incredibly proud of the work that went in to this, and love the direction the team has taken things since i stepped down.

**Comment by samccone** [comment]
:+1:

**Comment by jamesplease** [comment]
:blush:
