### ISSUE TITLE
Do you (still) use Marionette?

### ISSUE THREAD

**Issue by danmactough** [mxriverlynn/ama#2]
I'm assuming that when you were still working on it actively, you were also using it. :smile:

Now that it's not your baby, is it still your go-to framework? Or has Chuck talked you into using Angular?

Why/why not?

**Comment by mxriverlynn** [comment]
I do still use it, and it is my go-to for front-end JavaScript development. I'm doing a lot more than just front-end these days, so I don't get to use it as often as I would like... but it's still my primary choice.

I built Marionette because I liked the flexibility of Backbone, and saw the need for something as flexible but adding more on top. I still like Marionette for these reasons, compared to ember or angular or whatever else. It fits my way of thinking (as it should, since I built it :P) and the way I like to piecemeal components to create an architecture for a given application.

This is largely why I use Express on Node.js, instead of Sails... and why I used Sinatra on Ruby, instead of Rails. I like smaller parts that add up to more.

**Comment by danmactough** [comment]
> I like smaller parts that add up to more.

Word

**Comment by jamesplease** [comment]
> I do still use it, and it is my go-to for front-end JavaScript development. I'm doing a lot more than just front-end these days, so I don't get to use it as often as I would like... but it's still my primary choice.

I hope we're not messin' it up too much lol

:stuck_out_tongue:
