### ISSUE TITLE
A question I asked on facebook

### ISSUE THREAD

**Issue by BorisKozo** [mxriverlynn/ama#25]
I recently asked a question on Facebook which sparked some interesting exchange, I wonder what you think.
Original text (translated from Hebrew)
"If your application has no users and you spend quite some time optimizing its performance, did you optimize the performance at all?"

This is a paraphrase on the well known saying about a tree falling in the wood and no one hears it. This is sort of a catch 22, as long as your application has poor* performance it will not attract users but if you spend time optimizing performance on the wrong areas instead of making features that will attract users is it really a time well spent?

Would love to know what you think.

*poor is a matter of perspective... The load time is 4 seconds, is it poor? Can it be 2 seconds? Will it be poor then?

**Comment by mxriverlynn** [comment]
"If your application has no users and you spend quite some time optimizing its performance, did you optimize the performance at all?"

the short answer is, yes. you can optimize performance even if there are zero users. performance in software is an objectively measurable thing, in terms of time it takes to do something. 

but your other commentary hits the real issue: "is it really time well spent?" the short answer here, is no. unless you have users that are telling you the performance is insufficient (or other evidence - like a WebHook handler constantly causing errors, because it can't respond fast enough) it might not make sense to spend time optimizing it.

"as long as your application has poor performance it will not attract users"

this is almost categorically false for most software in the business world. with the exception of software in which performance is a critical feature, users are generally not attracted to performance characteristics of the software they use. they are attracted to the possibility of the software solving a problem for them. 

"poor is a matter of perspective"

that's the real key, here.

the performance on loading any given level of the Battlefield 1 video game is abysmal. it can take several minutes in some cases. but i sit there, and i wait and i put up with it day in and day out because i know the experience i'll have once the level has loaded will be worth it. 

but if a website takes 30 seconds to load? bye bye.

"load" is also a matter of perspective, though.

as long as you show something of value or something meaningful to the user, to let them know that the system is working and doing things, people are very forgiving if they believe they are about to receive the benefit they were promised.

but getting back to the original question, did you optimize the performance? yes. did you optimize the right thing? probably not. 

if you have no users, you either haven't marketed your product correctly or you are not solving a problem other people care about.

**Comment by BorisKozo** [comment]
Thanks :)
