### ISSUE TITLE
How did you get into programming?

### ISSUE THREAD

**Issue by sindresorhus** [mxriverlynn/ama#3]

**Comment by mxriverlynn** [comment]
when I was 10, my dad brought home a Commodore 64 computer from his work. it was originally set up in my brother's room, because he was older than me and would probably have more use for it right away. that quickly changed as I was constantly in his room and bothering him while I was pecking away at the keyboard. 

Shortly after that, my mom brought home a box full of C64 floppy disks and a C64 Basic book. I was nearly instantly hooked, as I spent hours re-typing code from the book to see what it would do, and then changing things to see what would happen.

From there, I moved up in the world to a 286 (again, from dad's work) with QBasic. I moved on to Turbo Pascal 5, 6 and 7 from there. I started doing assembly language in TP7 because I didn't like how slow the borland graphics libraries were for TP7 - so I wrote my own... remember, this was MS-DOS days with single-threaded, single-process systems. No GUI or anything...just raw 320x200 graphics mode and pushing pixels directly to the video card memory! 

From there, C/C++, QuickBasic, VisualBasic, ColdFusion (v1 or v2... don't remember exactly) as my first web programming language, PHP, classic ASP, and on and on and on...
