### ISSUE TITLE
How do you think we could do open source better?

### ISSUE THREAD

**Issue by sindresorhus** [mxriverlynn/ama#6]

**Comment by mxriverlynn** [comment]
by fostering a community of compassion and empathy, to help other developers see the reality of software as interaction between human beings and not simply a cold, impersonal "technical" act.

Too many privileged individuals are so very willing to assert that being nice or having empathy or dealing with the social issues and social nature of software and open source, are "not technical issues". This is pure fallacy. These privileged individuals are ignoring the culture that has propped them up and allowed them to thrive, at the expense of others. They see software and open source as "if you were just like me, you wouldn't have a problem" and are either unwilling or unable to see the reality that most of the world lives within.

I'm one of the offenders, by the way. I've been that guy far more times than I can count. It's hard not to be that way when our culture is set up to assume that my work is better than the work of others, simply because I was born a straight white male. 

Until we can foster a true sense of "us" and get rid of "them" in our language and culture, we will continue to fail so many people, as open source leaders and community members.

I talk about this a bit in my [5 Stages of Developer Grief](http://derickbailey.com/2015/03/29/the-5-stages-of-developer-grief-spacecityjs-2015-keynote/) keynote presentation from SpaceCityJS 2015. It's worth watching for anyone that wants to recognize the humanity that is software development, IMO.
